// Real dashboard and score endpoint, disposable local SQLite fixture only.
const {chromium}=require(process.argv[2]);
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try {
  const context=await browser.newContext({viewport:{width:1400,height:1050}});
  const page=await context.newPage(), base=process.argv[3], out=process.argv[4]; await fs.mkdir(out,{recursive:true});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  const token=(await (await context.request.get(base+'/session.php?id=1&reset=1')).json()).csrf;
  await page.goto(base+'/dashboard.php?student_id=2');
  const root=page.locator('#competency-browser');
  assert.equal(await root.locator('[data-competency]').count(),15);
  assert.equal(await root.locator('.competency-detail').count(),0);
  assert.equal(await page.locator('#curriculum-grid').isVisible(),false);
  await root.screenshot({path:out+'/competencies-list.png'});
  await root.getByRole('button',{name:'1. ASL Sentence Constructions',exact:true}).click();
  assert.equal(await root.locator('[data-element]').count(),9);
  await root.getByRole('button',{name:'WH-questions',exact:true}).click();
  assert.match(await root.locator('.competency-detail p').first().innerText(),/WH-questions/);
  await root.screenshot({path:out+'/competencies-elements.png'});
  await root.getByRole('button',{name:'Proficiency scale →',exact:true}).click();
  assert.equal(await root.locator('[data-competency]').count(),0);
  assert.deepEqual(await root.locator('.competency-score').allTextContents(),['1','2','3','4']);
  const saved=page.waitForResponse(r=>r.url().endsWith('/api/save_score.php'));
  await root.locator('[data-score="4"]').click(); const response=await saved; assert.equal(response.status(),200);
  await root.locator('[data-score="4"].selected').waitFor();
  await root.getByRole('button',{name:'Reception',exact:true}).click();
  assert.equal(await root.locator('.competency-level.selected').count(),0);
  const savedReception=page.waitForResponse(r=>r.url().endsWith('/api/save_score.php'));
  await root.locator('[data-score="2"]').click(); await savedReception;
  await root.locator('[data-score="2"].selected').waitFor();
  await root.screenshot({path:out+'/competencies-scale.png'});
  await page.reload();
  await root.getByRole('button',{name:'1. ASL Sentence Constructions',exact:true}).click();
  await root.getByRole('button',{name:'WH-questions',exact:true}).click();
  await root.getByRole('button',{name:'Proficiency scale →',exact:true}).click();
  assert.equal(await root.locator('[data-score="4"].selected').count(),1);
  await root.getByRole('button',{name:'Reception',exact:true}).click();
  assert.equal(await root.locator('[data-score="2"].selected').count(),1);
  const data=await page.evaluate(()=>dashboardData);
  const target=data.taxonomy[0].standards[0].targets[0].id;
  const post=async(form)=>context.request.post(base+'/api/save_score.php',{form:{student_id:'2',target_id:String(target),score:'3',csrf_token:token,...form}});
  assert.equal((await post({csrf_token:'invalid'})).status(),419);
  assert.equal((await post({score:'3.9'})).status(),400);
  assert.equal((await post({student_id:'3'})).status(),403);
  await root.getByRole('button',{name:'Return to competencies'}).click();
  assert.equal(await root.locator('.competency-detail').count(),0);
  await root.getByRole('button',{name:'6. Lexicalized Fingerspelling',exact:true}).click();
  assert.equal(await root.locator('[data-element]').count(),0);
  await root.getByRole('button',{name:'Proficiency scale →',exact:true}).click();
  assert.equal(await root.locator('.competency-level').count(),4);
  await root.getByRole('button',{name:'Return to competencies'}).click();
  await root.getByRole('button',{name:'12. Conversation Management',exact:true}).click();
  await root.locator('[data-element]').first().click(); await root.locator('.open-scale').click();
  assert.equal(await root.locator('[data-mode]').count(),0);
  await page.goto(base+'/dashboard.php?student_id=3');
  await root.getByRole('button',{name:'3. Organizing and Connecting Related Ideas',exact:true}).click();
  await root.locator('[data-element]').first().click(); await root.locator('.open-scale').click();
  assert.deepEqual(await root.locator('.competency-score').allTextContents(),['1','2','3']);
  const three=await page.evaluate(()=>dashboardData.taxonomy[0].standards.find(s=>s.competency.key==='connections').targets[0].id);
  assert.equal((await post({student_id:'3',target_id:String(three),score:'4'})).status(),400);
  await context.request.get(base+'/session.php?id=2'); await page.goto(base+'/dashboard.php');
  await root.getByRole('button',{name:'1. ASL Sentence Constructions',exact:true}).click();
  await root.getByRole('button',{name:'WH-questions',exact:true}).click(); await root.locator('.open-scale').click();
  assert.equal(await root.locator('[data-score]').count(),0);
  assert.equal(await root.locator('.competency-level.selected').count(),1);
  assert.equal((await post({})).status(),403);
  await page.locator('[data-range-toggle="progress"] [data-range="full"]').click();
  await page.locator('.chart-stage').screenshot({path:out+'/competencies-chart.png'});
  assert.equal(await page.locator('#progress-chart polygon').count(),1);
  assert.equal(await page.locator('#progress-chart polyline[stroke-width="2.5"]').count(),4);
  const fullPercent=await page.locator('#progress-chart circle[aria-label]').first().getAttribute('aria-label');
  await page.locator('[data-range-toggle="progress"] [data-range="ytd"]').click();
  assert.equal(await page.locator('#progress-chart circle[aria-label]').first().getAttribute('aria-label'),fullPercent,'current percentage does not change with date-range view');
  const references=await page.locator('#progress-chart polyline[stroke-width="2.5"]').evaluateAll(lines=>lines.map(line=>line.getAttribute('points').split(' ').map(p=>Number(p.split(',')[1]))));
  assert(references.every(([a,b])=>a===b),'grade references are horizontal');
  assert(Math.abs(references[1][0]-references[2][0])>60,'B and C have expanded separation');
  await page.setViewportSize({width:390,height:844}); await root.screenshot({path:out+'/competencies-mobile.png'});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true);
  assert.equal((await context.request.post(base+'/api/import_competencies.php',{form:{csrf_token:token}})).status(),403);
  await context.request.get(base+'/session.php?id=4');
  assert.equal((await context.request.post(base+'/api/import_competencies.php',{form:{csrf_token:token}})).status(),403);
  await context.request.get(base+'/session.php?id=1&reset_import=1');
  assert.equal((await context.request.post(base+'/api/import_competencies.php',{form:{csrf_token:'bad'}})).status(),419);
  await page.setViewportSize({width:1400,height:1050}); await page.goto(base+'/teacher/dashboard.php');
  const imported=page.waitForResponse(r=>r.url().endsWith('/api/import_competencies.php'));
  await page.getByRole('button',{name:'Import competencies',exact:true}).click();
  const importResponse=await imported; assert.equal(importResponse.status(),200,await importResponse.text());
  await page.locator('#import-competencies').waitFor({state:'detached'});
  await page.reload(); assert.equal(await page.locator('#import-competencies').count(),0);
  assert.equal((await context.request.post(base+'/api/import_competencies.php',{form:{csrf_token:token}})).status(),409);
  await page.goto(base+'/dashboard.php?student_id=2');
  assert.equal(await page.evaluate(()=>Object.values(dashboardData.scores).reduce((a,b)=>a+b,0)),6,'setup preserves prior grades');
  await page.goto(base+'/teacher/grading.php?level=1');
  assert.equal(await page.locator('.skill-head').count(),38);
  assert.equal((await page.locator('.skill-head').first().innerText()).trim(),'Basic declarative statements');
  await page.screenshot({path:out+'/teacher-grading.png',fullPage:true});
  const cell=page.locator('.grade-cell[data-student="2"]').first();
  for(const expected of [1,2,3,4,null]) {
    const saving=page.waitForResponse(r=>r.url().endsWith('/api/save_score.php'));
    await cell.click(); const saved=await (await saving).json(); assert.equal(saved.score,expected);
    await page.waitForFunction(()=>!document.querySelector('.grade-cell.saving'));
    assert.equal(await cell.getAttribute('data-score'),expected===null?'':String(expected));
    if(expected===null) assert.equal(saved.progress.overall.find(v=>v!==null),6,'clear removes contribution from current graph');
  }
  await page.reload(); assert.equal(await cell.getAttribute('data-score'),'');
  for(const expected of [4,3,2,1,null]) {
    const saving=page.waitForResponse(r=>r.url().endsWith('/api/save_score.php'));
    await cell.click({button:'right'}); assert.equal((await (await saving).json()).score,expected);
    await page.waitForFunction(()=>!document.querySelector('.grade-cell.saving'));
  }
  await page.getByRole('button',{name:'Reception',exact:true}).click(); await page.waitForURL('**mode=reception**');
  assert.equal(await page.locator('.skill-head').count(),38); assert.equal(await cell.getAttribute('data-score'),'');
  await page.getByRole('button',{name:'Other',exact:true}).click(); await page.waitForURL('**mode=other**');
  assert.equal(await page.locator('.skill-head').count(),13);
  assert.deepEqual(await page.locator('.competency-group-head').allTextContents(),['Conversation Management','Deaf History','Deaf Culture']);
  await page.goto(base+'/teacher/grading.php?level=3&standard=C3.connections&mode=expression');
  for(const expected of [1,2,3,null]) {
    const saving=page.waitForResponse(r=>r.url().endsWith('/api/save_score.php'));
    await page.locator('.grade-cell').first().click(); assert.equal((await (await saving).json()).score,expected);
    await page.waitForFunction(()=>!document.querySelector('.grade-cell.saving'));
  }
  await context.request.get(base+'/session.php?id=2'); await page.goto(base+'/dashboard.php');
  assert.equal(await page.evaluate(()=>Object.values(dashboardData.scores).reduce((a,b)=>a+b,0)),6,'cleared target absent on student reload');
  assert.equal((await post({score:''})).status(),403,'student cannot clear a score');
  assert.deepEqual(errors,[]);
  console.log('PASS teacher/student UI, separate modes, save/reload, singleton, absent 4, scope/CSRF authorization, chart and mobile');
 } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
