<?php
session_start();

// Check if user is logged in
if (!isset($_SESSION['logged_in']) || $_SESSION['logged_in'] !== true) {
    header('Location: ../../../index.php');
    exit;
}

$user = $_SESSION['user'];
$is_gm = ($user === 'GM');

// Check if user has access (only zepha and GM)
if ($user !== 'zepha' && !$is_gm) {
    echo '<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Access Restricted</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; padding: 50px; background-color: #f5f5f5; }
            .error-container { background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); max-width: 500px; margin: 0 auto; }
            .error-message { color: #d32f2f; font-size: 18px; margin-bottom: 20px; }
            .back-button { background: #1976d2; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; text-decoration: none; display: inline-block; }
        </style>
    </head>
    <body>
        <div class="error-container">
            <h1>Access Restricted</h1>
            <p class="error-message">Arcane Construction is only available to Zepha and the GM.</p>
            <a href="../../dashboard.php" class="back-button">Return to Dashboard</a>
        </div>
    </body>
    </html>';
    exit;
}

// Include version system
define('VERSION_SYSTEM_INTERNAL', true);
require_once '../../version.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arcane Construction</title>
    <link rel="stylesheet" href="css/arcaneconstruction.css">
</head>
<body>
    <div class="arcane-container">
        <header class="arcane-header">
            <h1>Arcane Construction</h1>
            <div class="header-controls">
                <span class="user-info">Welcome, <?php echo htmlspecialchars($user === 'GM' ? 'Game Master' : ucfirst($user)); ?></span>
                <?php if ($is_gm): ?>
                <button id="connect-btn" class="connect-btn">Connect</button>
                <?php endif; ?>
                <button onclick="window.close()" class="close-btn">Close</button>
            </div>
        </header>
        
        <main class="arcane-main">
            <div class="grid-viewport">
                <div class="grid-container">
                    <div class="construction-grid" id="construction-grid">
                        <!-- Grid will be generated by JavaScript -->
                    </div>
                    <!-- SVG overlay for arrows -->
                    <svg id="arrow-overlay" class="arrow-overlay">
                        <defs>
                            <marker id="arrowhead" markerWidth="10" markerHeight="7" 
                                    refX="10" refY="3.5" orient="auto">
                                <polygon points="0 0, 10 3.5, 0 7" fill="#dc2626" />
                            </marker>
                        </defs>
                    </svg>
                </div>
            </div>
        </main>
    </div>

    <!-- Version Display -->
    <div class="version-footer">
        <span class="version-info"><?php echo Version::displayVersion(); ?></span>
        <span class="version-updated">Updated: <?php echo Version::getLastUpdated(); ?></span>
    </div>

    <script>
        // Pass user information to JavaScript
        window.userRole = '<?php echo $is_gm ? 'GM' : 'zepha'; ?>';
        window.userName = '<?php echo htmlspecialchars($user); ?>';
    </script>
    <script src="js/arcaneconstruction.js"></script>
    <script>
        // Initialize the grid when page loads
        document.addEventListener('DOMContentLoaded', function() {
            initializeGrid();
        });
    </script>
</body>
</html>