<?php
session_start();

// Check if user is logged in
if (!isset($_SESSION['logged_in']) || $_SESSION['logged_in'] !== true) {
    header('Location: ../../../index.php');
    exit;
}

$user = $_SESSION['user'];
$is_gm = ($user === 'GM');

// Check if user has access (only zepha and GM)
if ($user !== 'zepha' && !$is_gm) {
    echo '<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Access Restricted</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; padding: 50px; background-color: #f5f5f5; }
            .error-container { background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); max-width: 500px; margin: 0 auto; }
            .error-message { color: #d32f2f; font-size: 18px; margin-bottom: 20px; }
            .back-button { background: #1976d2; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; text-decoration: none; display: inline-block; }
        </style>
    </head>
    <body>
        <div class="error-container">
            <h1>Access Restricted</h1>
            <p class="error-message">Arcane Construction is only available to Zepha and the GM.</p>
            <a href="../../dashboard.php" class="back-button">Return to Dashboard</a>
        </div>
    </body>
    </html>';
    exit;
}

// Include version system
define('VERSION_SYSTEM_INTERNAL', true);
require_once '../../version.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arcane Construction</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cinzel:wght@500;600;700;800&display=swap">
    <link rel="stylesheet" href="css/arcaneconstruction.css?v=<?php echo filemtime(__DIR__ . '/css/arcaneconstruction.css'); ?>">
</head>
<body class="<?php echo $is_gm ? 'role-gm' : 'role-zepha'; ?>">
    <div class="arcane-container">
        <header class="arcane-header">
            <div class="brand">
                <h1>Arcane Construction</h1>
                <span class="user-info">Welcome, <?php echo htmlspecialchars($user === 'GM' ? 'Game Master' : ucfirst($user)); ?></span>
            </div>
            <nav class="section-tabs" id="section-tabs" aria-label="Skill trees">
                <!-- Tabs for the four trees are added by JavaScript -->
            </nav>
            <div class="header-controls">
                <button id="links-btn" class="links-btn" title="Draw every connection at once">Show all links</button>
                <?php if ($is_gm): ?>
                <button id="connect-btn" class="connect-btn">Connect</button>
                <?php else: ?>
                <button id="learn-skill-btn" class="learn-skill-btn">Learn Skill</button>
                <?php endif; ?>
                <button id="help-btn" class="help-btn" title="Controls">?</button>
                <button onclick="window.close()" class="close-btn">Close</button>
            </div>
        </header>
        <div id="mode-banner" class="mode-banner" role="status"></div>

        <main class="arcane-main">
            <div class="board-wrap">
                <div class="grid-viewport">
                    <div class="grid-container">
                        <div class="construction-grid" id="construction-grid">
                            <!-- Grid will be generated by JavaScript -->
                        </div>
                        <!-- SVG overlay for connections - positioned inside grid container -->
                        <svg id="arrow-overlay" class="arrow-overlay">
                            <defs>
                                <marker id="arrowhead-plain" markerWidth="9" markerHeight="8" refX="7" refY="4" orient="auto" markerUnits="userSpaceOnUse">
                                    <polygon points="0 0, 9 4, 0 8" fill="#8f97a8" />
                                </marker>
                                <marker id="arrowhead-req" markerWidth="11" markerHeight="10" refX="8" refY="5" orient="auto" markerUnits="userSpaceOnUse">
                                    <polygon points="0 0, 11 5, 0 10" fill="#f2c45a" />
                                </marker>
                                <marker id="arrowhead-open" markerWidth="11" markerHeight="10" refX="8" refY="5" orient="auto" markerUnits="userSpaceOnUse">
                                    <polygon points="0 0, 11 5, 0 10" fill="#5fd3c4" />
                                </marker>
                            </defs>
                        </svg>
                    </div>
                </div>
            </div>

            <aside class="side-panel">
                <section id="progress" class="side-section"></section>
                <section id="inspector" class="side-section inspector"></section>
                <section id="benefits" class="side-section benefits"></section>
                <!-- Save Button -->
                <div class="save-container">
                    <button id="save-btn" class="save-btn">
                        <?php echo $is_gm ? 'Save Grid' : 'Save Skills'; ?>
                    </button>
                    <div id="save-status" class="save-status"></div>
                </div>
            </aside>
        </main>
    </div>

    <!-- Version Display -->
    <div class="version-footer">
        <span class="version-info"><?php echo Version::displayVersion(); ?></span>
        <span class="version-updated">Updated: <?php echo Version::getLastUpdated(); ?></span>
    </div>

    <script>
        // Pass user information to JavaScript
        window.userRole = '<?php echo $is_gm ? 'GM' : 'zepha'; ?>';
        window.userName = '<?php echo htmlspecialchars($user); ?>';
    </script>
    <script src="js/arcaneconstruction.js?v=<?php echo filemtime(__DIR__ . '/js/arcaneconstruction.js'); ?>"></script>
    <script>
        // Initialize the grid when page loads
        document.addEventListener('DOMContentLoaded', function() {
            initializeGrid();
        });
    </script>
</body>
</html>